// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./dev/styles/main.sass";

import Navbar from "../components/main/Navbar";
import Hero from '../components/main/Hero';
import OneStreamPlus from '../components/main/OneStreamPlus';
import OneStream from "../components/main/OneStream";
import Hospitality from "../components/main/Hospitality";

export const metadata = {
  title: "OneStream App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Hero />
        <OneStreamPlus />
        {/* <Tvc /> */}
        <OneStream />
        <Hospitality />
        <OneStream />
      </body>
    </html>
  );
}
